// Licensed to Julian Hyde under one or more contributor license
// agreements.  See the NOTICE file distributed with this work for
// additional information regarding copyright ownership. Julian Hyde
// licenses this file to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance with the
// License.  You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Code generated by tools/schema.py. DO NOT EDIT.

use crate::{Column, Table};

/// Every table in the data set, in alphabetical order.
pub static TABLES: [Table; 26] = [
    Table {
        name: "account",
        csv: include_str!("../csv/account.csv"),
        columns: &[
            Column {
                name: "account_id",
                sql_type: "INTEGER",
                not_null: true,
            },
            Column {
                name: "account_parent",
                sql_type: "INTEGER",
                not_null: false,
            },
            Column {
                name: "account_description",
                sql_type: "VARCHAR(30)",
                not_null: false,
            },
            Column {
                name: "account_type",
                sql_type: "VARCHAR(30)",
                not_null: true,
            },
            Column {
                name: "account_rollup",
                sql_type: "VARCHAR(30)",
                not_null: true,
            },
            Column {
                name: "Custom_Members",
                sql_type: "VARCHAR(255)",
                not_null: false,
            },
        ],
    },
    Table {
        name: "category",
        csv: include_str!("../csv/category.csv"),
        columns: &[
            Column {
                name: "category_id",
                sql_type: "VARCHAR(30)",
                not_null: true,
            },
            Column {
                name: "category_parent",
                sql_type: "VARCHAR(30)",
                not_null: false,
            },
            Column {
                name: "category_description",
                sql_type: "VARCHAR(30)",
                not_null: true,
            },
            Column {
                name: "category_rollup",
                sql_type: "VARCHAR(30)",
                not_null: false,
            },
        ],
    },
    Table {
        name: "currency",
        csv: include_str!("../csv/currency.csv"),
        columns: &[
            Column {
                name: "currency_id",
                sql_type: "INTEGER",
                not_null: true,
            },
            Column {
                name: "date",
                sql_type: "DATE",
                not_null: true,
            },
            Column {
                name: "currency",
                sql_type: "VARCHAR(30)",
                not_null: true,
            },
            Column {
                name: "conversion_ratio",
                sql_type: "DECIMAL(10,4)",
                not_null: true,
            },
        ],
    },
    Table {
        name: "customer",
        csv: include_str!("../csv/customer.csv"),
        columns: &[
            Column {
                name: "customer_id",
                sql_type: "INTEGER",
                not_null: true,
            },
            Column {
                name: "account_num",
                sql_type: "BIGINT",
                not_null: true,
            },
            Column {
                name: "lname",
                sql_type: "VARCHAR(30)",
                not_null: true,
            },
            Column {
                name: "fname",
                sql_type: "VARCHAR(30)",
                not_null: true,
            },
            Column {
                name: "mi",
                sql_type: "VARCHAR(30)",
                not_null: false,
            },
            Column {
                name: "address1",
                sql_type: "VARCHAR(30)",
                not_null: false,
            },
            Column {
                name: "address2",
                sql_type: "VARCHAR(30)",
                not_null: false,
            },
            Column {
                name: "address3",
                sql_type: "VARCHAR(30)",
                not_null: false,
            },
            Column {
                name: "address4",
                sql_type: "VARCHAR(30)",
                not_null: false,
            },
            Column {
                name: "city",
                sql_type: "VARCHAR(30)",
                not_null: false,
            },
            Column {
                name: "state_province",
                sql_type: "VARCHAR(30)",
                not_null: false,
            },
            Column {
                name: "postal_code",
                sql_type: "VARCHAR(30)",
                not_null: true,
            },
            Column {
                name: "country",
                sql_type: "VARCHAR(30)",
                not_null: true,
            },
            Column {
                name: "customer_region_id",
                sql_type: "INTEGER",
                not_null: true,
            },
            Column {
                name: "phone1",
                sql_type: "VARCHAR(30)",
                not_null: true,
            },
            Column {
                name: "phone2",
                sql_type: "VARCHAR(30)",
                not_null: true,
            },
            Column {
                name: "birthdate",
                sql_type: "DATE",
                not_null: true,
            },
            Column {
                name: "marital_status",
                sql_type: "VARCHAR(30)",
                not_null: true,
            },
            Column {
                name: "yearly_income",
                sql_type: "VARCHAR(30)",
                not_null: true,
            },
            Column {
                name: "gender",
                sql_type: "VARCHAR(30)",
                not_null: true,
            },
            Column {
                name: "total_children",
                sql_type: "SMALLINT",
                not_null: true,
            },
            Column {
                name: "num_children_at_home",
                sql_type: "SMALLINT",
                not_null: true,
            },
            Column {
                name: "education",
                sql_type: "VARCHAR(30)",
                not_null: true,
            },
            Column {
                name: "date_accnt_opened",
                sql_type: "DATE",
                not_null: true,
            },
            Column {
                name: "member_card",
                sql_type: "VARCHAR(30)",
                not_null: false,
            },
            Column {
                name: "occupation",
                sql_type: "VARCHAR(30)",
                not_null: false,
            },
            Column {
                name: "houseowner",
                sql_type: "VARCHAR(30)",
                not_null: false,
            },
            Column {
                name: "num_cars_owned",
                sql_type: "INTEGER",
                not_null: false,
            },
            Column {
                name: "fullname",
                sql_type: "VARCHAR(60)",
                not_null: true,
            },
        ],
    },
    Table {
        name: "days",
        csv: include_str!("../csv/days.csv"),
        columns: &[
            Column {
                name: "day",
                sql_type: "INTEGER",
                not_null: true,
            },
            Column {
                name: "week_day",
                sql_type: "VARCHAR(30)",
                not_null: true,
            },
        ],
    },
    Table {
        name: "department",
        csv: include_str!("../csv/department.csv"),
        columns: &[
            Column {
                name: "department_id",
                sql_type: "INTEGER",
                not_null: true,
            },
            Column {
                name: "department_description",
                sql_type: "VARCHAR(30)",
                not_null: true,
            },
        ],
    },
    Table {
        name: "employee",
        csv: include_str!("../csv/employee.csv"),
        columns: &[
            Column {
                name: "employee_id",
                sql_type: "INTEGER",
                not_null: true,
            },
            Column {
                name: "full_name",
                sql_type: "VARCHAR(30)",
                not_null: true,
            },
            Column {
                name: "first_name",
                sql_type: "VARCHAR(30)",
                not_null: true,
            },
            Column {
                name: "last_name",
                sql_type: "VARCHAR(30)",
                not_null: true,
            },
            Column {
                name: "position_id",
                sql_type: "INTEGER",
                not_null: false,
            },
            Column {
                name: "position_title",
                sql_type: "VARCHAR(30)",
                not_null: false,
            },
            Column {
                name: "store_id",
                sql_type: "INTEGER",
                not_null: true,
            },
            Column {
                name: "department_id",
                sql_type: "INTEGER",
                not_null: true,
            },
            Column {
                name: "birth_date",
                sql_type: "DATE",
                not_null: true,
            },
            Column {
                name: "hire_date",
                sql_type: "TIMESTAMP",
                not_null: false,
            },
            Column {
                name: "end_date",
                sql_type: "TIMESTAMP",
                not_null: false,
            },
            Column {
                name: "salary",
                sql_type: "DECIMAL(10,4)",
                not_null: true,
            },
            Column {
                name: "supervisor_id",
                sql_type: "INTEGER",
                not_null: false,
            },
            Column {
                name: "education_level",
                sql_type: "VARCHAR(30)",
                not_null: true,
            },
            Column {
                name: "marital_status",
                sql_type: "VARCHAR(30)",
                not_null: true,
            },
            Column {
                name: "gender",
                sql_type: "VARCHAR(30)",
                not_null: true,
            },
            Column {
                name: "management_role",
                sql_type: "VARCHAR(30)",
                not_null: false,
            },
        ],
    },
    Table {
        name: "employee_closure",
        csv: include_str!("../csv/employee_closure.csv"),
        columns: &[
            Column {
                name: "employee_id",
                sql_type: "INTEGER",
                not_null: true,
            },
            Column {
                name: "supervisor_id",
                sql_type: "INTEGER",
                not_null: true,
            },
            Column {
                name: "distance",
                sql_type: "INTEGER",
                not_null: false,
            },
        ],
    },
    Table {
        name: "expense_fact",
        csv: include_str!("../csv/expense_fact.csv"),
        columns: &[
            Column {
                name: "store_id",
                sql_type: "INTEGER",
                not_null: true,
            },
            Column {
                name: "account_id",
                sql_type: "INTEGER",
                not_null: true,
            },
            Column {
                name: "exp_date",
                sql_type: "TIMESTAMP",
                not_null: true,
            },
            Column {
                name: "time_id",
                sql_type: "INTEGER",
                not_null: true,
            },
            Column {
                name: "category_id",
                sql_type: "VARCHAR(30)",
                not_null: true,
            },
            Column {
                name: "currency_id",
                sql_type: "INTEGER",
                not_null: true,
            },
            Column {
                name: "amount",
                sql_type: "DECIMAL(10,4)",
                not_null: true,
            },
        ],
    },
    Table {
        name: "inventory_fact_1997",
        csv: include_str!("../csv/inventory_fact_1997.csv"),
        columns: &[
            Column {
                name: "product_id",
                sql_type: "INTEGER",
                not_null: true,
            },
            Column {
                name: "time_id",
                sql_type: "INTEGER",
                not_null: false,
            },
            Column {
                name: "warehouse_id",
                sql_type: "INTEGER",
                not_null: false,
            },
            Column {
                name: "store_id",
                sql_type: "INTEGER",
                not_null: false,
            },
            Column {
                name: "units_ordered",
                sql_type: "INTEGER",
                not_null: false,
            },
            Column {
                name: "units_shipped",
                sql_type: "INTEGER",
                not_null: false,
            },
            Column {
                name: "warehouse_sales",
                sql_type: "DECIMAL(10,4)",
                not_null: false,
            },
            Column {
                name: "warehouse_cost",
                sql_type: "DECIMAL(10,4)",
                not_null: false,
            },
            Column {
                name: "supply_time",
                sql_type: "SMALLINT",
                not_null: false,
            },
            Column {
                name: "store_invoice",
                sql_type: "DECIMAL(10,4)",
                not_null: false,
            },
        ],
    },
    Table {
        name: "inventory_fact_1998",
        csv: include_str!("../csv/inventory_fact_1998.csv"),
        columns: &[
            Column {
                name: "product_id",
                sql_type: "INTEGER",
                not_null: true,
            },
            Column {
                name: "time_id",
                sql_type: "INTEGER",
                not_null: false,
            },
            Column {
                name: "warehouse_id",
                sql_type: "INTEGER",
                not_null: false,
            },
            Column {
                name: "store_id",
                sql_type: "INTEGER",
                not_null: false,
            },
            Column {
                name: "units_ordered",
                sql_type: "INTEGER",
                not_null: false,
            },
            Column {
                name: "units_shipped",
                sql_type: "INTEGER",
                not_null: false,
            },
            Column {
                name: "warehouse_sales",
                sql_type: "DECIMAL(10,4)",
                not_null: false,
            },
            Column {
                name: "warehouse_cost",
                sql_type: "DECIMAL(10,4)",
                not_null: false,
            },
            Column {
                name: "supply_time",
                sql_type: "SMALLINT",
                not_null: false,
            },
            Column {
                name: "store_invoice",
                sql_type: "DECIMAL(10,4)",
                not_null: false,
            },
        ],
    },
    Table {
        name: "position",
        csv: include_str!("../csv/position.csv"),
        columns: &[
            Column {
                name: "position_id",
                sql_type: "INTEGER",
                not_null: true,
            },
            Column {
                name: "position_title",
                sql_type: "VARCHAR(30)",
                not_null: true,
            },
            Column {
                name: "pay_type",
                sql_type: "VARCHAR(30)",
                not_null: true,
            },
            Column {
                name: "min_scale",
                sql_type: "DECIMAL(10,4)",
                not_null: true,
            },
            Column {
                name: "max_scale",
                sql_type: "DECIMAL(10,4)",
                not_null: true,
            },
            Column {
                name: "management_role",
                sql_type: "VARCHAR(30)",
                not_null: true,
            },
        ],
    },
    Table {
        name: "product",
        csv: include_str!("../csv/product.csv"),
        columns: &[
            Column {
                name: "product_class_id",
                sql_type: "INTEGER",
                not_null: true,
            },
            Column {
                name: "product_id",
                sql_type: "INTEGER",
                not_null: true,
            },
            Column {
                name: "brand_name",
                sql_type: "VARCHAR(60)",
                not_null: false,
            },
            Column {
                name: "product_name",
                sql_type: "VARCHAR(60)",
                not_null: true,
            },
            Column {
                name: "SKU",
                sql_type: "BIGINT",
                not_null: true,
            },
            Column {
                name: "SRP",
                sql_type: "DECIMAL(10,4)",
                not_null: false,
            },
            Column {
                name: "gross_weight",
                sql_type: "DOUBLE",
                not_null: false,
            },
            Column {
                name: "net_weight",
                sql_type: "DOUBLE",
                not_null: false,
            },
            Column {
                name: "recyclable_package",
                sql_type: "BOOLEAN",
                not_null: false,
            },
            Column {
                name: "low_fat",
                sql_type: "BOOLEAN",
                not_null: false,
            },
            Column {
                name: "units_per_case",
                sql_type: "SMALLINT",
                not_null: false,
            },
            Column {
                name: "cases_per_pallet",
                sql_type: "SMALLINT",
                not_null: false,
            },
            Column {
                name: "shelf_width",
                sql_type: "DOUBLE",
                not_null: false,
            },
            Column {
                name: "shelf_height",
                sql_type: "DOUBLE",
                not_null: false,
            },
            Column {
                name: "shelf_depth",
                sql_type: "DOUBLE",
                not_null: false,
            },
        ],
    },
    Table {
        name: "product_class",
        csv: include_str!("../csv/product_class.csv"),
        columns: &[
            Column {
                name: "product_class_id",
                sql_type: "INTEGER",
                not_null: true,
            },
            Column {
                name: "product_subcategory",
                sql_type: "VARCHAR(30)",
                not_null: false,
            },
            Column {
                name: "product_category",
                sql_type: "VARCHAR(30)",
                not_null: false,
            },
            Column {
                name: "product_department",
                sql_type: "VARCHAR(30)",
                not_null: false,
            },
            Column {
                name: "product_family",
                sql_type: "VARCHAR(30)",
                not_null: false,
            },
        ],
    },
    Table {
        name: "promotion",
        csv: include_str!("../csv/promotion.csv"),
        columns: &[
            Column {
                name: "promotion_id",
                sql_type: "INTEGER",
                not_null: true,
            },
            Column {
                name: "promotion_district_id",
                sql_type: "INTEGER",
                not_null: false,
            },
            Column {
                name: "promotion_name",
                sql_type: "VARCHAR(30)",
                not_null: false,
            },
            Column {
                name: "media_type",
                sql_type: "VARCHAR(30)",
                not_null: false,
            },
            Column {
                name: "cost",
                sql_type: "DECIMAL(10,4)",
                not_null: false,
            },
            Column {
                name: "start_date",
                sql_type: "TIMESTAMP",
                not_null: false,
            },
            Column {
                name: "end_date",
                sql_type: "TIMESTAMP",
                not_null: false,
            },
        ],
    },
    Table {
        name: "region",
        csv: include_str!("../csv/region.csv"),
        columns: &[
            Column {
                name: "region_id",
                sql_type: "INTEGER",
                not_null: true,
            },
            Column {
                name: "sales_city",
                sql_type: "VARCHAR(30)",
                not_null: false,
            },
            Column {
                name: "sales_state_province",
                sql_type: "VARCHAR(30)",
                not_null: false,
            },
            Column {
                name: "sales_district",
                sql_type: "VARCHAR(30)",
                not_null: false,
            },
            Column {
                name: "sales_region",
                sql_type: "VARCHAR(30)",
                not_null: false,
            },
            Column {
                name: "sales_country",
                sql_type: "VARCHAR(30)",
                not_null: false,
            },
            Column {
                name: "sales_district_id",
                sql_type: "INTEGER",
                not_null: false,
            },
        ],
    },
    Table {
        name: "reserve_employee",
        csv: include_str!("../csv/reserve_employee.csv"),
        columns: &[
            Column {
                name: "employee_id",
                sql_type: "INTEGER",
                not_null: true,
            },
            Column {
                name: "full_name",
                sql_type: "VARCHAR(30)",
                not_null: true,
            },
            Column {
                name: "first_name",
                sql_type: "VARCHAR(30)",
                not_null: true,
            },
            Column {
                name: "last_name",
                sql_type: "VARCHAR(30)",
                not_null: true,
            },
            Column {
                name: "position_id",
                sql_type: "INTEGER",
                not_null: false,
            },
            Column {
                name: "position_title",
                sql_type: "VARCHAR(30)",
                not_null: false,
            },
            Column {
                name: "store_id",
                sql_type: "INTEGER",
                not_null: true,
            },
            Column {
                name: "department_id",
                sql_type: "INTEGER",
                not_null: true,
            },
            Column {
                name: "birth_date",
                sql_type: "TIMESTAMP",
                not_null: true,
            },
            Column {
                name: "hire_date",
                sql_type: "TIMESTAMP",
                not_null: false,
            },
            Column {
                name: "end_date",
                sql_type: "TIMESTAMP",
                not_null: false,
            },
            Column {
                name: "salary",
                sql_type: "DECIMAL(10,4)",
                not_null: true,
            },
            Column {
                name: "supervisor_id",
                sql_type: "INTEGER",
                not_null: false,
            },
            Column {
                name: "education_level",
                sql_type: "VARCHAR(30)",
                not_null: true,
            },
            Column {
                name: "marital_status",
                sql_type: "VARCHAR(30)",
                not_null: true,
            },
            Column {
                name: "gender",
                sql_type: "VARCHAR(30)",
                not_null: true,
            },
        ],
    },
    Table {
        name: "salary",
        csv: include_str!("../csv/salary.csv"),
        columns: &[
            Column {
                name: "pay_date",
                sql_type: "TIMESTAMP",
                not_null: true,
            },
            Column {
                name: "employee_id",
                sql_type: "INTEGER",
                not_null: true,
            },
            Column {
                name: "department_id",
                sql_type: "INTEGER",
                not_null: true,
            },
            Column {
                name: "currency_id",
                sql_type: "INTEGER",
                not_null: true,
            },
            Column {
                name: "salary_paid",
                sql_type: "DECIMAL(10,4)",
                not_null: true,
            },
            Column {
                name: "overtime_paid",
                sql_type: "DECIMAL(10,4)",
                not_null: true,
            },
            Column {
                name: "vacation_accrued",
                sql_type: "DOUBLE",
                not_null: true,
            },
            Column {
                name: "vacation_used",
                sql_type: "DOUBLE",
                not_null: true,
            },
        ],
    },
    Table {
        name: "sales_fact_1997",
        csv: include_str!("../csv/sales_fact_1997.csv"),
        columns: &[
            Column {
                name: "product_id",
                sql_type: "INTEGER",
                not_null: true,
            },
            Column {
                name: "time_id",
                sql_type: "INTEGER",
                not_null: true,
            },
            Column {
                name: "customer_id",
                sql_type: "INTEGER",
                not_null: true,
            },
            Column {
                name: "promotion_id",
                sql_type: "INTEGER",
                not_null: true,
            },
            Column {
                name: "store_id",
                sql_type: "INTEGER",
                not_null: true,
            },
            Column {
                name: "store_sales",
                sql_type: "DECIMAL(10,4)",
                not_null: true,
            },
            Column {
                name: "store_cost",
                sql_type: "DECIMAL(10,4)",
                not_null: true,
            },
            Column {
                name: "unit_sales",
                sql_type: "DECIMAL(10,4)",
                not_null: true,
            },
        ],
    },
    Table {
        name: "sales_fact_1998",
        csv: include_str!("../csv/sales_fact_1998.csv"),
        columns: &[
            Column {
                name: "product_id",
                sql_type: "INTEGER",
                not_null: true,
            },
            Column {
                name: "time_id",
                sql_type: "INTEGER",
                not_null: true,
            },
            Column {
                name: "customer_id",
                sql_type: "INTEGER",
                not_null: true,
            },
            Column {
                name: "promotion_id",
                sql_type: "INTEGER",
                not_null: true,
            },
            Column {
                name: "store_id",
                sql_type: "INTEGER",
                not_null: true,
            },
            Column {
                name: "store_sales",
                sql_type: "DECIMAL(10,4)",
                not_null: true,
            },
            Column {
                name: "store_cost",
                sql_type: "DECIMAL(10,4)",
                not_null: true,
            },
            Column {
                name: "unit_sales",
                sql_type: "DECIMAL(10,4)",
                not_null: true,
            },
        ],
    },
    Table {
        name: "sales_fact_dec_1998",
        csv: include_str!("../csv/sales_fact_dec_1998.csv"),
        columns: &[
            Column {
                name: "product_id",
                sql_type: "INTEGER",
                not_null: true,
            },
            Column {
                name: "time_id",
                sql_type: "INTEGER",
                not_null: true,
            },
            Column {
                name: "customer_id",
                sql_type: "INTEGER",
                not_null: true,
            },
            Column {
                name: "promotion_id",
                sql_type: "INTEGER",
                not_null: true,
            },
            Column {
                name: "store_id",
                sql_type: "INTEGER",
                not_null: true,
            },
            Column {
                name: "store_sales",
                sql_type: "DECIMAL(10,4)",
                not_null: true,
            },
            Column {
                name: "store_cost",
                sql_type: "DECIMAL(10,4)",
                not_null: true,
            },
            Column {
                name: "unit_sales",
                sql_type: "DECIMAL(10,4)",
                not_null: true,
            },
        ],
    },
    Table {
        name: "store",
        csv: include_str!("../csv/store.csv"),
        columns: &[
            Column {
                name: "store_id",
                sql_type: "INTEGER",
                not_null: true,
            },
            Column {
                name: "store_type",
                sql_type: "VARCHAR(30)",
                not_null: false,
            },
            Column {
                name: "region_id",
                sql_type: "INTEGER",
                not_null: false,
            },
            Column {
                name: "store_name",
                sql_type: "VARCHAR(30)",
                not_null: false,
            },
            Column {
                name: "store_number",
                sql_type: "INTEGER",
                not_null: false,
            },
            Column {
                name: "store_street_address",
                sql_type: "VARCHAR(30)",
                not_null: false,
            },
            Column {
                name: "store_city",
                sql_type: "VARCHAR(30)",
                not_null: false,
            },
            Column {
                name: "store_state",
                sql_type: "VARCHAR(30)",
                not_null: false,
            },
            Column {
                name: "store_postal_code",
                sql_type: "VARCHAR(30)",
                not_null: false,
            },
            Column {
                name: "store_country",
                sql_type: "VARCHAR(30)",
                not_null: false,
            },
            Column {
                name: "store_manager",
                sql_type: "VARCHAR(30)",
                not_null: false,
            },
            Column {
                name: "store_phone",
                sql_type: "VARCHAR(30)",
                not_null: false,
            },
            Column {
                name: "store_fax",
                sql_type: "VARCHAR(30)",
                not_null: false,
            },
            Column {
                name: "first_opened_date",
                sql_type: "TIMESTAMP",
                not_null: false,
            },
            Column {
                name: "last_remodel_date",
                sql_type: "TIMESTAMP",
                not_null: false,
            },
            Column {
                name: "store_sqft",
                sql_type: "INTEGER",
                not_null: false,
            },
            Column {
                name: "grocery_sqft",
                sql_type: "INTEGER",
                not_null: false,
            },
            Column {
                name: "frozen_sqft",
                sql_type: "INTEGER",
                not_null: false,
            },
            Column {
                name: "meat_sqft",
                sql_type: "INTEGER",
                not_null: false,
            },
            Column {
                name: "coffee_bar",
                sql_type: "BOOLEAN",
                not_null: false,
            },
            Column {
                name: "video_store",
                sql_type: "BOOLEAN",
                not_null: false,
            },
            Column {
                name: "salad_bar",
                sql_type: "BOOLEAN",
                not_null: false,
            },
            Column {
                name: "prepared_food",
                sql_type: "BOOLEAN",
                not_null: false,
            },
            Column {
                name: "florist",
                sql_type: "BOOLEAN",
                not_null: false,
            },
        ],
    },
    Table {
        name: "store_ragged",
        csv: include_str!("../csv/store_ragged.csv"),
        columns: &[
            Column {
                name: "store_id",
                sql_type: "INTEGER",
                not_null: true,
            },
            Column {
                name: "store_type",
                sql_type: "VARCHAR(30)",
                not_null: false,
            },
            Column {
                name: "region_id",
                sql_type: "INTEGER",
                not_null: false,
            },
            Column {
                name: "store_name",
                sql_type: "VARCHAR(30)",
                not_null: false,
            },
            Column {
                name: "store_number",
                sql_type: "INTEGER",
                not_null: false,
            },
            Column {
                name: "store_street_address",
                sql_type: "VARCHAR(30)",
                not_null: false,
            },
            Column {
                name: "store_city",
                sql_type: "VARCHAR(30)",
                not_null: false,
            },
            Column {
                name: "store_state",
                sql_type: "VARCHAR(30)",
                not_null: false,
            },
            Column {
                name: "store_postal_code",
                sql_type: "VARCHAR(30)",
                not_null: false,
            },
            Column {
                name: "store_country",
                sql_type: "VARCHAR(30)",
                not_null: false,
            },
            Column {
                name: "store_manager",
                sql_type: "VARCHAR(30)",
                not_null: false,
            },
            Column {
                name: "store_phone",
                sql_type: "VARCHAR(30)",
                not_null: false,
            },
            Column {
                name: "store_fax",
                sql_type: "VARCHAR(30)",
                not_null: false,
            },
            Column {
                name: "first_opened_date",
                sql_type: "TIMESTAMP",
                not_null: false,
            },
            Column {
                name: "last_remodel_date",
                sql_type: "TIMESTAMP",
                not_null: false,
            },
            Column {
                name: "store_sqft",
                sql_type: "INTEGER",
                not_null: false,
            },
            Column {
                name: "grocery_sqft",
                sql_type: "INTEGER",
                not_null: false,
            },
            Column {
                name: "frozen_sqft",
                sql_type: "INTEGER",
                not_null: false,
            },
            Column {
                name: "meat_sqft",
                sql_type: "INTEGER",
                not_null: false,
            },
            Column {
                name: "coffee_bar",
                sql_type: "BOOLEAN",
                not_null: false,
            },
            Column {
                name: "video_store",
                sql_type: "BOOLEAN",
                not_null: false,
            },
            Column {
                name: "salad_bar",
                sql_type: "BOOLEAN",
                not_null: false,
            },
            Column {
                name: "prepared_food",
                sql_type: "BOOLEAN",
                not_null: false,
            },
            Column {
                name: "florist",
                sql_type: "BOOLEAN",
                not_null: false,
            },
        ],
    },
    Table {
        name: "time_by_day",
        csv: include_str!("../csv/time_by_day.csv"),
        columns: &[
            Column {
                name: "time_id",
                sql_type: "INTEGER",
                not_null: true,
            },
            Column {
                name: "the_date",
                sql_type: "TIMESTAMP",
                not_null: false,
            },
            Column {
                name: "the_day",
                sql_type: "VARCHAR(30)",
                not_null: false,
            },
            Column {
                name: "the_month",
                sql_type: "VARCHAR(30)",
                not_null: false,
            },
            Column {
                name: "the_year",
                sql_type: "SMALLINT",
                not_null: false,
            },
            Column {
                name: "day_of_month",
                sql_type: "SMALLINT",
                not_null: false,
            },
            Column {
                name: "week_of_year",
                sql_type: "INTEGER",
                not_null: false,
            },
            Column {
                name: "month_of_year",
                sql_type: "SMALLINT",
                not_null: false,
            },
            Column {
                name: "quarter",
                sql_type: "VARCHAR(30)",
                not_null: false,
            },
            Column {
                name: "fiscal_period",
                sql_type: "VARCHAR(30)",
                not_null: false,
            },
        ],
    },
    Table {
        name: "warehouse",
        csv: include_str!("../csv/warehouse.csv"),
        columns: &[
            Column {
                name: "warehouse_id",
                sql_type: "INTEGER",
                not_null: true,
            },
            Column {
                name: "warehouse_class_id",
                sql_type: "INTEGER",
                not_null: false,
            },
            Column {
                name: "stores_id",
                sql_type: "INTEGER",
                not_null: false,
            },
            Column {
                name: "warehouse_name",
                sql_type: "VARCHAR(60)",
                not_null: false,
            },
            Column {
                name: "wa_address1",
                sql_type: "VARCHAR(30)",
                not_null: false,
            },
            Column {
                name: "wa_address2",
                sql_type: "VARCHAR(30)",
                not_null: false,
            },
            Column {
                name: "wa_address3",
                sql_type: "VARCHAR(30)",
                not_null: false,
            },
            Column {
                name: "wa_address4",
                sql_type: "VARCHAR(30)",
                not_null: false,
            },
            Column {
                name: "warehouse_city",
                sql_type: "VARCHAR(30)",
                not_null: false,
            },
            Column {
                name: "warehouse_state_province",
                sql_type: "VARCHAR(30)",
                not_null: false,
            },
            Column {
                name: "warehouse_postal_code",
                sql_type: "VARCHAR(30)",
                not_null: false,
            },
            Column {
                name: "warehouse_country",
                sql_type: "VARCHAR(30)",
                not_null: false,
            },
            Column {
                name: "warehouse_owner_name",
                sql_type: "VARCHAR(30)",
                not_null: false,
            },
            Column {
                name: "warehouse_phone",
                sql_type: "VARCHAR(30)",
                not_null: false,
            },
            Column {
                name: "warehouse_fax",
                sql_type: "VARCHAR(30)",
                not_null: false,
            },
        ],
    },
    Table {
        name: "warehouse_class",
        csv: include_str!("../csv/warehouse_class.csv"),
        columns: &[
            Column {
                name: "warehouse_class_id",
                sql_type: "INTEGER",
                not_null: true,
            },
            Column {
                name: "description",
                sql_type: "VARCHAR(30)",
                not_null: false,
            },
        ],
    },
];

// End schema.rs
